name: Update README with Repository Name

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update README
        run: |
          sed -i "s#{{REPO_NAME}}#eric-zamora-tech/new-repo-template#g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "eric.zamora.in@gmail.com"
          git config --local user.name "eric-zamora-tech"
          git add README.md
          git commit -m "Updated README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
