name: Update README with Repository Name

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Extract and Format Repository Name
        id: extract_repo_name
        run: |
          # Extract repository name (last part of the path)
          REPO_NAME="${{ github.repository }}"
          LAST_PART=$(echo "$REPO_NAME" | awk -F'/' '{print $2}')
          
          # Format the name (remove hyphens, convert to lowercase)
          FORMATTED_NAME=$(echo "$LAST_PART" | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          echo "FORMATTED_NAME=${FORMATTED_NAME}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s#{{REPO_NAME}}#${{ env.FORMATTED_NAME }}#g" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "eric.zamora.in@gmail.com"
          git config --local user.name "eric-zamora-tech"
          git add README.md
          git commit -m "Updated README with formatted repository name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
